### ISSUE TITLE
How to set hyperparameter like gamma, sigma_end etc.?

### ISSUE THREAD

**Issue by liuyezhou** [Newbeeer/Poisson_flow#9]
Hi, Could you please provide code of calculating average l2 norm on CIFAR-10? Thanks!

**Comment by Newbeeer** [comment]
Hi,

I calculated the l2 norm in another private project, and it's hard to elegantly integrate the code into current repo.

The calculation is pretty easy: (1) Setup a data loader for CIFAR-10; (2) Enumerate over the data points in CIFAR-10 to calculate the l2 norm. 

Yilun

**Comment by liuyezhou** [comment]
Hi, 

It's great job and thank your kindly reply! 

I try to adopt your implementation to TTS/VC duty,  and here is my part hyperparameter setting：
```yaml
tau: 0.03 
data_norm: 9     # l2 normalization on hidden state by each frame
data_dim: 256    # hidden state channel
```

Could you give any advice about how to set other hyperparameter like gamma, sigma_end etc.? 

Yezhou
